### ISSUE TITLE
"all_processing" function error

### ISSUE THREAD

**Issue by ForceField17** [beroukhim-lab/BISCUT-py3#1]
Dear authors, I tried your code with your demo data. However, the error below stop me from reproducing the results.

> all_processing(thedate, ci, qval_thres, selectedgenes, all_arms, genelocs_file, abslocs_file)
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: No objects to concatenate
Run `reticulate::py_last_error()` for details.

> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "combine_BISCUT_results.py", line 878, in all_processing
    make_table_results(folder,kspval, qval_thres)
  File "combine_BISCUT_results.py", line 96, in make_table_results
    combined = pd.concat(alldfs)
  File "/Users/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/miniconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/Users/miniconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate (local) all_processing(...)
 2.   └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by shahab-sarmashghi** [comment]
It could be the previous steps haven't been run successfully, or simply they are not at the correct path. If you're running the code on the demo data with the same arguments, you should have the following result directory structure at the time of running `all_processing()` function:
- results_date_ci/
  - KS_pvalues_date_ci.txt
  - PANCAN
    - PANCAN_1p_amp_cent_n_0.95_iter1.pdf
    - PANCAN_1p_amp_cent_n_0.95_iter1.txt
    - ...
  - stats
    - PANCAN_1p_amp_cent_n_1.rds
    - PANCAN_1p_amp_cent_n-ln_2.rds
    - ...

If so, then the rest of the code will use these files to summarize the results. Can you check to see if these files exist?

**Comment by ForceField17** [comment]
Thanks so much for your response.

I can get the .pdf files in the PANCAN  folder, but the .txt files are not exist there.
<img width="1747" alt="image" src="https://github.com/beroukhim-lab/BISCUT-py3/assets/40787414/4a2a197b-c575-49df-a578-481a7362bf6f">

**Comment by AliceAntonello** [comment]
Hello, 

I had the same error on the demo data. I downloaded the example data and placed it in the '/docs' folder, then I ran `python3 BISCUT_preprocessing.py` and a `breakpoint_files_2022_07_26` was created in the main folder. Inside it there is a PANCAN folder containing 156 .txt files named 'PANCAN_1p_amp_cent.txt'. I then ran the `BISCUT_peak_finding.R` from Rstudio and got an error at line 629:

`Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
ValueError: No objects to concatenate
Run `reticulate::py_last_error()` for details.
6.
stop(<environment>)
5.
__init__ at concat.py#429
4.
concat at concat.py#372
3.
make_table_results at combine_BISCUT_results.py#96
2.
all_processing at combine_BISCUT_results.py#878
1.
all_processing(thedate, ci, qval_thres, selectedgenes, all_arms,
genelocs_file, abslocs_file)`

At this point, in the 'results_2022_07_26_0.95' folder I find :

- KS_pvalues_2022_07_26_0.95.txt
- PANCAN folder with 156 .pdf files named something like 'PANCAN_1q_amp_tel_p_0.95_iter1.pdf' and an empty 'summary' folder
- stat folder with 156 .rds files with names like 'PANCAN_1p_amp_cent_n_1.rds' and an empty 'summary' folder

Thank you for the support

**Comment by shahab-sarmashghi** [comment]
Hi folks,

I cannot reproduce this error on my side. I just re-ran the code on another machine from the scratch to make sure I do not have some settings on my laptop that you are missing but I didn't get any errors. My run produced 768 `pdf` and 306 `txt` files under `PANCAN/` and 768 `rds` files under `stats/`. Although you are getting the error at the next step which is running a python code and makes me wonder if the issue is with `python` version or a library like `pandas`, but I also do not understand why the part of code before the error generates so few peaks?

- Can you double check the output logs and see if you get any error in the steps leading to running `all_processing()` function? Trying to understand the reason you get so few peaks.
- What versions of `python` and `pandas` are you using?

**Comment by AliceAntonello** [comment]
Hello, 

I am using Python 3.10.10 and pandas  1.5.3. I looked into the BISCUT_processing.py function to better understand what it does. When it generates the arm_list, the result is a list of strings with 39 (amp) +39 (del) entries: ['13', '14','15','21’, …]. For each, it then produces two data frames (psedftel, psedfcent) looking like :
￼

And saves them in the ‘breakpoint_files_date’ folder, where at the end of the run I find 39*2*2 = 156 files, without giving any error. When I then run BISCUT_peak_finding.R, I get 156 pdf files in the ‘results/PANCAN’ directory and 156 rds files in the ‘results/stats’ directory plus two empty summary directories in each.

**Comment by shahab-sarmashghi** [comment]
The pre-processing step should generate exactly 156 files as you mentioned: 39 chromosome arms * 2 tel/cent * 2 amp/del. However, `BISCUT_peak_finding.R` should generate many more peaks under `results/PANCAN` and `results/stats` before the `all_processing()` step. The way the algorithm works is that for any of those 156 combinations iteratively looks for loci under selection. Does it ever go past the first peak, i.e., any files with iter2 or higher suffix? My suspicion is that there are errors for each arm_tel/cent_amp/del combination beyond iteration 1, but they are caught with `tryCatch` so no exception has been raised until you see the error in the next step `all_processing`. Can you change the line 639 from:
`bar <- tryCatch(do_arm_gistic(a,tumor_type,d,tc,mode='overlap'),error=errorfunc)`
to:
`bar <- do_arm_gistic(a,tumor_type,d,tc,mode='overlap')`
and see if you get any error? If not, try to do the same with lines 616 and 617 and run it again. This might help to see where the error is.

**Comment by shahab-sarmashghi** [comment]
Hi folks, did you have a chance to try this? I'd love to help you run BISCUT but right now I don't know the root cause of that error. There might be some unseen error because of that `tryCatch` statement so disabling it might help us to identify the underlying issue. Let me know. Thanks!

**Comment by shahab-sarmashghi** [comment]
Hi @ForceField17 and @AliceAntonello,

I think I have found the problem with the help of another user who was running into a similar error. It's a silly problem with a print statement which for some reason gives error when using the latest version of R 4.3.1. It was working just fine with the recommended version of R 4.1.2 mentioned in the README. Please pull the changes and let me know if the issues is resolved. Thanks!

**Comment by PollyHung** [comment]
> The pre-processing step should generate exactly 156 files as you mentioned: 39 chromosome arms * 2 tel/cent * 2 amp/del. However, `BISCUT_peak_finding.R` should generate many more peaks under `results/PANCAN` and `results/stats` before the `all_processing()` step. The way the algorithm works is that for any of those 156 combinations iteratively looks for loci under selection. Does it ever go past the first peak, i.e., any files with iter2 or higher suffix? My suspicion is that there are errors for each arm_tel/cent_amp/del combination beyond iteration 1, but they are caught with `tryCatch` so no exception has been raised until you see the error in the next step `all_processing`. Can you change the line 639 from: `bar <- tryCatch(do_arm_gistic(a,tumor_type,d,tc,mode='overlap'),error=errorfunc)` to: `bar <- do_arm_gistic(a,tumor_type,d,tc,mode='overlap')` and see if you get any error? If not, try to do the same with lines 616 and 617 and run it again. This might help to see where the error is.

Hi, I've experienced the same error running your code. And I've tried to track down where it went wrong, and here is what I got "> foreach(i=1:length(all_arms)) %dopar% {
+   a <- all_arms[i]
+   for (d in c('amp','del')) {
+     for (tc in c('cent','tel')) {
+       # bar <- tryCatch(do_arm_gistic(a,tumor_type,d,tc,mode='overlap'),error=errorfunc)
+       bar <- do_arm_gistic(a,tumor_type,d,tc,mode='overlap')
+     }
+   }
+ }
Error in { : task 1 failed - "$ operator is invalid for atomic vectors"
> traceback()
3: stop(simpleError(msg, call = expr))
2: e$fun(obj, substitute(ex), parent.frame(), e$data)
1: foreach(i = 1:length(all_arms)) %dopar% {
       a <- all_arms[i]
       for (d in c("amp", "del")) {
           for (tc in c("cent", "tel")) {
               bar <- do_arm_gistic(a, tumor_type, d, tc, mode = "overlap")
           }
       }
   }" Could you please help take a look this error?
