### ISSUE TITLE
how to prepare the file of chromosome_coordinates for hg38

### ISSUE THREAD

**Issue by lemon-latte** [beroukhim-lab/BISCUT-py3#3]
Hi,
  I am trying to use BISCUT to get breakpoint for my data. But I am confused for some cloumns in the file of chromosome_coordinates (ex. q_start1, q_end1, offset, cent_mod), could you please give me some explaintation for the cloumns so that I can do futher steps

**Comment by shahab-sarmashghi** [comment]
See https://github.com/beroukhim-lab/BISCUT-py3/issues/2#issuecomment-1664664340. In general though it shouldn't make a large difference to use hg19-based coordinates provided. Just remember to use hg38-based gene list.
